### ISSUE TITLE
/root/SimpleTuner/.venv/lib/python3.11/site-packages/nvidia/nvjitlink/lib Unknown optimizer requested: adamw_bf16

### ISSUE THREAD

**Issue by Blackfox2012** [AmericanPresidentJimmyCarter/simple-flux-lora-training#1]
/root/SimpleTuner/.venv/lib/python3.11/site-packages/nvidia/nvjitlink/lib
Unknown optimizer requested: adamw_bf16

**Comment by Blackfox2012** [comment]
when bash train.sh

**Comment by Blackfox2012** [comment]
running pytorch/pytorch_2.4.0-cuda12.4-cudnn9-devel/jupyter

**Comment by AmericanPresidentJimmyCarter** [comment]
https://github.com/bghira/SimpleTuner/blob/1380f113e67ee80d215c31f4aefe089892936da0/train.sh#L256-L258

That error message comes from here and it looks correct. I'll ask @bghira. You can also come to the discord server: https://discord.com/invite/cSmvcU9Me9

**Comment by bghira** [comment]
try `bash -x train.sh`

**Comment by AmericanPresidentJimmyCarter** [comment]
Haven't heard anything back so closing.
