### ISSUE TITLE
Torch.tensor issue

### ISSUE THREAD

**Issue by bplrdev** [AmericanPresidentJimmyCarter/simple-flux-lora-training#2]
Thanks for your work, it helps a lot! ❤ My first lora came out 10/10 yesterday, following your guide.

However, today I'm getting these warnings on each training steps:

```
Steps:   1%|_                                  | 64/5000 [19:45<24:36:41, 17.95s/it, lr=0.0001, step_loss=0.384]Passing `txt_ids` 3d torch.Tensor is deprecated.Please remove the batch dimension and pass it as a 2d torch Tensor
Passing `img_ids` 3d torch.Tensor is deprecated.Please remove the batch dimension and pass it as a 2d torch Tensor
```
Is there any fix for that? Also, does it affects the training itself?

**Comment by AmericanPresidentJimmyCarter** [comment]
It does not affect training. It's just a deprecation warning in SimpleTuner that will be patched in the next release. You can ignore it.

**Comment by bplrdev** [comment]
Thank you!
